package com.ai.geminiIntegration;

import com.ai.geminiIntegration.dto.AIRequest;
import com.ai.geminiIntegration.dto.AIResponse;
import com.ai.geminiIntegration.util.AIRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.gson.Gson;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import javax.net.ssl.SSLContext;
import org.apache.http.conn.ssl.SSLConnectionSocketFactory;
import org.apache.http.conn.ssl.TrustStrategy;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.springframework.http.*;
import org.springframework.http.client.HttpComponentsClientHttpRequestFactory;
import org.springframework.web.client.RestTemplate;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import static com.ai.geminiIntegration.util.ApplicationConstants.API_KEY;
import static com.ai.geminiIntegration.util.ApplicationConstants.GEMINI_API_URL;

@SpringBootApplication
public class GeminiIntegrationApplication {

	//Retrieve API Key from DB
	private static final String apiKey = AIRepository.getInstance().retrieveAIInformation(API_KEY);
	private static Scanner sc = new Scanner(System.in);

	public static void main(String[] args) throws Exception {
		startApplication();
		sc.close();
	}

	/**
	 * Created this method to start the application because I need to execute this logic
	 * more than once. If the user wants to ask additional questions, then I can just
	 * call this method again to start the whole process from scratch.
	 *
	 * @throws Exception
	 */
	private static void startApplication() throws Exception {
		System.out.println("What would you like to search:");
		openConnection(sc.nextLine());
		//making sure everything is done executing before continuing flow of application
		Thread.sleep(500);
		System.out.println("Do you have any additional questions? [Y] or [N]");
		continueCommunication(sc.nextLine());
	}

	/**
	 * Restarts flow of application if user needs to ask additional questions
	 * @param userInput "Y" or "N" input to determine if application needs to continue running
	 * @throws Exception
	 */
	private static void continueCommunication(String userInput) throws Exception {
		switch (userInput) {
			case "Y":
				startApplication();
				break;
			case "N":
				System.err.println("[Closing Communication]");
				break;
			default:
				System.err.println("[Incorrect Input] \n" + "Stopping Application...");
				break;
		}
	}

	/**
	 * Establish communication with Gemini API
	 * @param input User prompt
	 * @throws Exception
	 */
	private static void openConnection(String input) throws Exception {
		String url = GEMINI_API_URL.concat(apiKey);
		String finalRequest = new ObjectMapper().writeValueAsString(updateRequest(input));
		RestTemplate template = getRestTemplate(url);
		HttpEntity<String> request = new HttpEntity<>(finalRequest, initClientHeaders());
		ResponseEntity<String> response = template.postForEntity(url, request, String.class);
		extractResponse(response.getBody());
	}

	/**
	 * Creating request with all the required fields
	 * @param input User prompt
	 * @return AI Request object
	 */
	static AIRequest updateRequest(String input) {
		// Create an instance of AIRequest
		AIRequest aiRequest = new AIRequest();

		// Create a Part object and set the text
		AIRequest.Part part = new AIRequest.Part();
		part.setText(input);

		// Create a Content object and add the Part to it
		AIRequest.Content content = new AIRequest.Content();
		List<AIRequest.Part> parts = new ArrayList<>();
		parts.add(part);
		content.setParts(parts);

		// Add the Content to the AIRequest
		List<AIRequest.Content> contents = new ArrayList<>();
		contents.add(content);
		aiRequest.setContents(contents);

		return aiRequest;
	}

	/**
	 * Converting raw json into java class -> then extracting certain data from fields
	 * @param rawJSONResponse
	 */
	private static void extractResponse(String rawJSONResponse) {
		try {
			//Deserializing AI raw json response into java class
			AIResponse aiResponse = new Gson().fromJson(rawJSONResponse, AIResponse.class);

			//Extract Candidate Object from Candidates List
			AIResponse.Candidate candidate = aiResponse.candidates.get(0);

			//Extracting text that contains the AI Response
			System.out.println("Extracted Explanation: \n" + candidate.content.parts.get(0).text);

			//Extracting additional metadata from response
			List<AIResponse.CitationSource> sources = candidate.citationMetadata.citationSources;
			//Extracting URI links from metadata section in AI Response
			System.out.println("Extracted URIs:");
			for (AIResponse.CitationSource source : sources) {
				System.out.println(source.uri);
			}
		} catch (Exception e) {
			System.err.println("Extracted URL section empty due to response being generated by Gemini AI");
		}
	}

	// set default HTTP headers
	private static HttpHeaders initClientHeaders() {
		final HttpHeaders headers = new HttpHeaders();
		headers.setContentType(MediaType.APPLICATION_JSON);
		headers.add("key", apiKey);
		return headers;
	}

	/**
	 * Create RestTemplate with HTTP or HTTPS based on URL
	 *
	 * @param url is the which will be process for the REST template
	 * @return a URL-based RestTemplate
	 * @throws Exception
	 */
	private static RestTemplate getRestTemplate(String url) throws Exception {
		String urlPattern = "^(http|https|ftp)://.*$";
		if (url.matches(urlPattern)) {
			final TrustStrategy acceptingTrustStrategy = (cert, authType) -> true;

			SSLContext sslContext = org.apache.http.ssl.SSLContexts.custom()
					.loadTrustMaterial(null, acceptingTrustStrategy)
					.build();

			SSLConnectionSocketFactory csf = new SSLConnectionSocketFactory(sslContext);

			CloseableHttpClient httpClient = HttpClients.custom()
					.setSSLSocketFactory(csf)
					.build();

			HttpComponentsClientHttpRequestFactory requestFactory =
					new HttpComponentsClientHttpRequestFactory();

			requestFactory.setHttpClient(httpClient);
			return new RestTemplate(requestFactory);
		}

		return new RestTemplate();
	}

}
