package com.ai.geminiIntegration;

import com.ai.geminiIntegration.dto.AIRequest;
import com.ai.geminiIntegration.dto.AIResponse;
import com.ai.geminiIntegration.util.AIRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.gson.Gson;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import javax.net.ssl.SSLContext;
import org.apache.http.conn.ssl.SSLConnectionSocketFactory;
import org.apache.http.conn.ssl.TrustStrategy;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.springframework.http.*;
import org.springframework.http.client.HttpComponentsClientHttpRequestFactory;
import org.springframework.web.client.RestTemplate;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import static com.ai.geminiIntegration.util.ApplicationConstants.API_KEY;
import static com.ai.geminiIntegration.util.ApplicationConstants.GEMINI_API_URL;

@SpringBootApplication
public class GeminiIntegrationApplication {

	private static final String apiKey = AIRepository.getInstance().retrieveAIInformation(API_KEY);

	public static void main(String[] args) throws Exception {
		System.out.println("What would you like to search:");
		Scanner sc = new Scanner(System.in);
		testConnection(sc.nextLine());
		sc.close();
	}

	private static void testConnection(String input) throws Exception {
		String url = GEMINI_API_URL.concat(apiKey);
		String finalRequest = new ObjectMapper().writeValueAsString(updateRequest(input));
		RestTemplate template = getRestTemplate(url);
		HttpEntity<String> request = new HttpEntity<>(finalRequest, initClientHeaders());
		ResponseEntity<String> response = template.postForEntity(url, request, String.class);
		extractResponse(response.getBody());
	}

	static AIRequest updateRequest(String input) {
		// Create an instance of AIRequest
		AIRequest aiRequest = new AIRequest();

		// Create a Part object and set the text
		AIRequest.Part part = new AIRequest.Part();
		part.setText(input);

		// Create a Content object and add the Part to it
		AIRequest.Content content = new AIRequest.Content();
		List<AIRequest.Part> parts = new ArrayList<>();
		parts.add(part);
		content.setParts(parts);

		// Add the Content to the AIRequest
		List<AIRequest.Content> contents = new ArrayList<>();
		contents.add(content);
		aiRequest.setContents(contents);

		// Print the value to verify
		//System.out.println("Text: " + aiRequest.getContents().get(0).getParts().get(0).getText());
		return aiRequest;
	}

	private static void extractResponse(String rawJSONResponse) {
		try {
			Gson gson = new Gson();
			AIResponse aiResponse = gson.fromJson(rawJSONResponse, AIResponse.class);

			// Example: Accessing the first part's text
			String text = aiResponse.candidates.get(0).content.parts.get(0).text;
			System.out.println("Extracted Explanation: \n" + text);

			// Step 4: Extract and print URI fields
			List<AIResponse.CitationSource> sources =
					aiResponse.candidates.get(0).citationMetadata.citationSources;

			System.out.println("Extracted URIs:");
			for (AIResponse.CitationSource source : sources) {
				System.out.println(source.uri);
			}
		} catch (Exception e) {
			System.err.println("Extracted URL section empty due to response being generated by Gemini AI");
		}
	}

	// set default HTTP headers
	private static HttpHeaders initClientHeaders() {
		final HttpHeaders headers = new HttpHeaders();
		headers.setContentType(MediaType.APPLICATION_JSON);
		headers.add("key", apiKey);
		return headers;
	}

	/**
	 * Create RestTemplate with HTTP or HTTPS based on URL
	 *
	 * @param url is the which will be process for the REST template
	 * @return a URL-based RestTemplate
	 * @throws Exception
	 */
	private static RestTemplate getRestTemplate(String url) throws Exception {
		String urlPattern = "^(http|https|ftp)://.*$";
		if (url.matches(urlPattern)) {
			final TrustStrategy acceptingTrustStrategy = (cert, authType) -> true;

			SSLContext sslContext = org.apache.http.ssl.SSLContexts.custom()
					.loadTrustMaterial(null, acceptingTrustStrategy)
					.build();

			SSLConnectionSocketFactory csf = new SSLConnectionSocketFactory(sslContext);

			CloseableHttpClient httpClient = HttpClients.custom()
					.setSSLSocketFactory(csf)
					.build();

			HttpComponentsClientHttpRequestFactory requestFactory =
					new HttpComponentsClientHttpRequestFactory();

			requestFactory.setHttpClient(httpClient);
			return new RestTemplate(requestFactory);
		}

		return new RestTemplate();
	}

}
